#!/bin/sh
# Installation aliases
alias xi="sudo pacman -S"
alias xr="sudo pacman -Suy"

# power aliases
alias pow="poweroff"
alias reb="reboot"
alias asdf="startx"

# file aliases
alias ls="ls --color"
alias ls-="ls"
alias la="ls -A --color"
alias ll="ls -lA -h --color"
alias wl="ls -A --color | wc -l"
alias ..="cd .."
alias lb="cd ~/.local/bin"

# LaTeX aliases
alias tx="cp $HOME/dox/sample.tex" # personal file/script, see other repository
alias xl="xelatex"
alias pl="pdflatex"
alias pkg="nvim $HOME/dox/etc/pkg" # package count tracker
alias texclean="rm *.aux *.fdb_latexmk *.fls *.log *.synctex.gz" # gets rid of unessential LaTeX compilation files

# Programs
alias clock="tty-clock -S -s -c -C 6"
alias SM="mw -Y;neomutt" # Luke Smith's muttwizard sync command
alias v="nvim"
alias z="setsid zathura"
alias m="mpv"
alias pm="pulsemixer"
alias moc="mocp -O MOCDir=\"~/.config\"/moc"
alias cc="calcurse" # unused

# conveniency aliases
alias mus="cd $HOME/dox/media/mus/"
alias pod="cd $HOME/dox/media/podcasts/"
alias vids="cd $HOME/dox/media/videos/"
alias yt="cd $HOME/dox/media/videos/yt/"
alias www="cd $HOME/dox/www/"
alias s="setsid -f"
alias xreload="xrdb ~/.config/.Xresources"
alias pv="pipe-viewer --resolution 480"
alias zal="nvim $HOME/.config/zsh/aliasrc"

# make
alias mci="sudo make clean install"
alias mi="sudo make install"

# anti-retarded alias
alias cal="cal --monday"
